sudo: false
language: python
cache: pip
matrix:
    include:
        - python: 2.6
        - python: 2.7
        - python: 3.3
        - python: 3.4
        - python: 3.5
        # - language: generic
        #   os: osx
        #   env: PYVER=py26
        - language: generic
          os: osx
          env: PYVER=py27
        # - language: generic
        #   os: osx
        #   env: PYVER=py33
        - language: generic
          os: osx
          env: PYVER=py34
        # XXX - not supported yet
        # - language: generic
        #   os: osx
        #   env: PYVER=py35
install:
    - ./.ci/travis/install.sh
script:
    - ./.ci/travis/run.sh
after_success:
    - coveralls  # upload reports to coveralls.io
